---
- name: Ensure /etc/environment exists
  ansible.builtin.copy:
    content: ""
    dest: /etc/environment
    force: false
    group: root
    owner: root
    mode: 0644

- name: Add global variables
  ansible.builtin.lineinfile:
    dest: "/etc/environment"
    state: present
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
  with_items: "{{ os_environment }}"
