---
name: remove old package versions
on:
  # every day at 01:30am
  schedule:
    - cron: '30 1 * * *'
  # or manually
  workflow_dispatch:
jobs:
  remove-old-packages:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Delete the packages
    steps:
      - uses: actions/delete-package-versions@e5bc658cc4c965c472efe991f8beea3981499c55 # v5.0.0
        with:
          package-name: xyz.adrp.iac.ansible-system-config
          package-type: maven
          min-versions-to-keep: 5
          ignore-versions: '^([0-9]\\d*)\\.([0-9]\\d*)\\.([0-9]\\d*)$'
